name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'

    - name: Fetch dependencies
      run: |
        go get -u golang.org/x/lint/golint

    - name: Build
      run: go build .

    - name: Test With Coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: web, server
        fail_ci_if_error: true

    - name: Vet & Lint
      run: |
        go vet ./...

    - name: Lint
      run: |
        golint -set_exit_status=1 ./...
